### PR TITLE
FSA22V2-314: Refactor: Invert colors for component cards

### PR DESCRIPTION
**Pull request by marissahuysentruyt**
### Description:

To better match the light and dark mode color schemes, the component card colors were inverted and corresponding pink SVG's were added to the homepage. 

### Spec:

Designs: [Figma](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=84%3A270&t=vcD5FiaV9837qW9W-0)

See Story: [FSA22V2-314](https://sparkbox.atlassian.net/browse/FSA22V2-314)

### Validation:

- [x] This PR has code changes, and our linters still pass.
- [x] This PR affects production code, so it was browser tested (see below).

#### To Validate:

1. Make sure all PR Checks have passed (GitHub Actions, CircleCI, Code Climate, etc).
2. Pull down all related branches.
3. Run `npm install` to make sure you have all proper dependencies. (this project requires Node 16+)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to your newly created `.env.local` file. That should establish your connection to our Airtable database.
5. Run `npm run lint` to confirm no errors.
6. Run `npm run test` to confirm all tests pass.
7. In terminal: `npm run dev`.
8. Check [localhost:3000](http://localhost:3000/) to see changes.
9. Run axe Devtools on affected pages to confirm no urgent errors.
10. Switch back and forth between light & dark mode to confirm new inverted colors.

### Pending Questions:

1.
2.

---

#### Browser Testing

In these browsers, behavior & design closely match original specifications. A user is able to access all content and functionality, including the usability of required assistive devices, such as keyboard and screenreader.

**macOS**

- [x] Safari (latest version)
- [x] Chrome (latest version)
- [x] Firefox (latest version)
- [x] Edge (latest version)

**Windows**

- [ ] Chrome (last 6 months)
- [ ] Firefox (last 6 months)

**Mobile**

- [x] Safari (local version)
- [x] Chrome on Android (local version)
- [x] Firefox on Android (local version)

### CODE REVIEW

**Review by jkohrt7 — CHANGES_REQUESTED** [review]
I noticed the pink svgs were larger than the green ones and was able to optimize them a bit with SVGOMG. After I send them to you, could you replace the old images?

Also, thank you for removing those unused pngs--those totally slipped by me!

**Comment by marissahuysentruyt** [comment]
@jkohrt7  made those changes in https://github.com/sparkbox/accessible-components/pull/127/commits/8215bfd1c4dbc1030ecd6328abbe5b93bb2d2069 
Thanks for doing the optimizations!

**Review by jkohrt7 — APPROVED** [review]
Looks good, thanks for swapping those svgs out!

**Review by spina-goodyear — COMMENTED** [review]
Ooo this looks awesome, great job!
Untitled

**Review by saashapina — DISMISSED** [review]

**Review by saashapina — APPROVED** [review]

**Review by jkohrt7 — APPROVED** [review]

**Pull request merged**
