### PR TITLE
feat: set dynamic routes

### PR DESCRIPTION
**Pull request by tisidro**
### Description:
Set up component details page.

### Spec:
Designs: [Designs](DESIGN_URL)

See Story: [FSA22V2-218](https://sparkbox.atlassian.net/browse/FSA22V2-218?atlOrigin=eyJpIjoiZmRkYWIxMTgzNGExNDM1ZmIxZjk0NTZkMjk3ZGI1YTEiLCJwIjoiaiJ9)

### Validation:

* [ ] This PR has code changes, and our linters still pass.
* [ ] This PR affects production code, so it was browser tested (see below).
* [ ] This PR has new code, so new tests were added or updated, and they pass.

#### To Validate:

1. Make sure all PR Checks have passed (GitHub Actions, CircleCI, Code Climate, etc).
2. Pull down all related branches.
3. In terminal: `npm run dev`.
4. Check [localhost: 3000](http://localhost:3000/) for changes.
5. Run `npm run lint`.
6. Run axe DevTools on affected pages.
7. Confirm all tests pass.

Check that dynamic route page where details function returns an id dynamically based on the router query in an h1 tag.
---

#### Browser Testing

In these browsers, behavior & design closely match original specifications. A user is able to access all content and functionality, including the usability of required assistive devices, such as keyboard and screenreader.

**macOS**

* [x] Safari (last 2 major versions)
* [x] Chrome (last 6 months)
* [x] Firefox (last 6 months)

**Windows**

* [ ] Chrome (last 6 months)
* [ ] Firefox (last 6 months)
* [ ] Edge (last 6 months)

**Mobile**

* [ ] Safari (last 2 major versions)
* [ ] Chrome on Android (last 6 months)
* [ ] Firefox on Android (last 6 months)

### CODE REVIEW

**Comment by tisidro** [comment]
Note: Dustin said to hold off on making the Axe Devtools pass for now.

**Review by bsmrdel101 — DISMISSED** [review]
The routing worked for me, although keep in mind we may have to go back and change some of our syntax depending on what the js linter says. When that gets merged in.

**Comment by tisidro** [comment]
> The routing worked for me, although keep in mind we may have to go back and change some of our syntax depending on what the js linter says. When that gets merged in.

Not sure how this could be changed, the Next.js is very strict about what it looks for to render those routes. I wrote this straight from the docs.

I also wonder if I need to write some kind of test for this, though it works. Is this even testable? I'll ask in the apprentice channel or standup

**Review by empee3 — DISMISSED** [review]

**Review by bsmrdel101 — APPROVED** [review]
Looks good or something like that.

**Pull request merged**
