### PR TITLE
CI check for commit formatting

### PR DESCRIPTION
**Pull request by bsmrdel101**
### Description:
Github action will check if the commit messages are formatted correctly.

### Spec:

See Story: [FSA22V2-231](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-231)

### Validation:

* [x] This PR has code changes, and our linters still pass.
* [x] This PR has new code, so new tests were added or updated, and they pass.

#### To Validate:

1. Make sure all PR Checks have passed (GitHub Actions, CircleCI, Code Climate, etc).
2. Commit Message CI check below should not be failing because it has a proper commit title.

### CODE REVIEW

**Review by jkohrt7 — APPROVED** [review]
I tested the regex against a few commits, and they only matched the ones I expected them to. I'm glad you added the exception for those emojis--Marissa'll appreciate that 😄 

I also read a couple relevant pages about github jobs and couldn't find anything here that looked unusual. Good work!

**Review by jkohrt7 — COMMENTED** [review]
This is super nitpicky, but could you change 'added' to 'add' in the commit message?

**Comment by bengoshow** [comment]
> This is super nitpicky, but could you change 'added' to 'add' in the commit message?

Great point from @jkohrt7 - here is some more information on using the "Imperative Tone" when writing your commit messages and subjects: https://www.theserverside.com/video/Follow-these-git-commit-message-guidelines#:~:text=If%20you%20want%20to%20write,Instead%2C%20describe%20what%20was%20done.

**Review by jkohrt7 — APPROVED** [review]
Looks good! Thanks @bengoshow for clarifying--I'll try to give some reasoning for my suggestions next time.

**Pull request merged**
