### PR TITLE
Feat: Add support for Sandpack code examples

### PR DESCRIPTION
**Pull request by marissahuysentruyt**
### Description:

After exploring the viability of [Sandpack](https://sandpack.codesandbox.io/docs/), we've decided to move forward with it! Sandpack will now house the individual component code examples, instead of having them listed out on the page. A color theme was selected based on low color contrast accessibility issues found, Additionally, after working with WAS-certified developers, some of the styles and options (like adding focus-states & removing certain optional buttons) have been adjusted to make the experience as seamless as possible for users. 

As we were implementing Sandpack, we noticed there were quite serious issues with pa11y as our automated accessibility checking. We found it to be too inconsistent and unreliable. This branch has removed pa11y checks, and we are replacing it with Cypress on the main branch currently. 

**This PR review does not have to be a deep dive into the code! Most of the work had been approved on 2 separate branches already.

### Spec:

See Stories: 
[FSA22V2-299](https://sparkbox.atlassian.net/browse/FSA22V2-299)
[FSA22V2-300](https://sparkbox.atlassian.net/browse/FSA22V2-300)
[FSA22V2-309](https://sparkbox.atlassian.net/browse/FSA22V2-309)

### Validation:

- [x] This PR has code changes, and our linters still pass.
- [x] This PR affects production code, so it was browser tested (see below).
- [ ] This PR has new code, so new tests were added or updated, and they pass.

#### To Validate:

1. Make sure all PR Checks have passed (GitHub Actions, CircleCI, Code Climate, etc).
2. Pull down all related branches.
3. Run `npm install` to make sure you have all proper dependencies. (this project requires Node 16+)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to your newly created `.env.local` file. That should establish your connection to our Airtable database.
5. Run `npm run lint` to confirm no errors.
6. Run `npm run test` to confirm all tests pass.
7. In terminal: `npm run dev`.
8. Check [localhost:3000](http://localhost:3000/) to see changes.
9. Run axe Devtools on details pages to confirm there are no errors related to Sandpack.
10. On each individual component page, you should be able to see & interact with a Sandpack editor, and a live example of the component!

#### Pending Questions
1. Because we aren't using the `Code Block` components any longer, should those be deleted? 
---

#### Browser Testing

In these browsers, behavior & design closely match original specifications. A user is able to access all content and functionality, including the usability of required assistive devices, such as keyboard and screenreader.

**macOS**

- [x] Safari (last 2 major versions)
- [x] Chrome (last 6 months)
- [x] Firefox (last 6 months)

**Windows**

- [x] Chrome (last 6 months)
- [x] Firefox (last 6 months)
- [x] Edge (last 6 months)

**Mobile**

- [x] Safari (last 2 major versions)
- [x] Chrome on Android (last 6 months)
- [x] Firefox on Android (last 6 months)

### CODE REVIEW

**Review by tisidro — COMMENTED** [review]
Everything looks great with the sandpack code examples, and I was able to use it on each component. I was also able to navigate the tabs example. Great work on this!! :D

I did find some errors on axeDevTools  pertaining to "scrollable region must have keyboard access" and "aria attributes must conform to valid values." Are you seeing these too? If not, please lmk if you wanted to do a quick zoom and I'll show you what I found. 

image

image

image

**Review by tisidro — COMMENTED** [review]
On Accordion, I'm only seeing the one error below:
image

Also getting the scrollable error on dialog:
image

I am not getting the error on the disclosure page!

**Comment by marissahuysentruyt** [comment]
@tisidro I have answers to the axe errors!

1. The `.cm-scroller` error is referring to a nested div within the sandpack code editor. `.cm-scroller` doesn't show up on every component because every component's code editor might not scroll. After talking with Kasey about it, and explaining that the code editor _does_ have keyboard focus (just at the higher `.sp-code-editor` level), and how to access the inner editor (you can press `esc` or `enter`), she thought we could ignore that error message. Instead we added the new `figure`, and `figcaption` instructions to make it clearer how to access the editor from the keyboard. 
https://github.com/sparkbox/accessible-components/pull/123/commits/e9ce7e571a24ef7d43fddff99b49692c0d84fe64

2. The other ARIA error is a warning that our Tabs component had used `aria-labelledby`. That `aria-labelledby` didn't correspond to any other element, however. I still need someone to review the change I made, but because that `aria-labelledby` didn't match an `id` of any other element, I believe I can delete it to get rid of that error. 
3. https://github.com/sparkbox/accessible-components/pull/123/commits/da21c0b024f097b5a9a9abf353d75016c5a8019c

**Review by lahernandezb — APPROVED** [review]

**Review by tisidro — DISMISSED** [review]
This looks great! I still see the errors on AxeDevtools but figured those are fine for now, maybe something to keep on the backburner. Awesome job on this complex PR! :) :)

**Pull request merged**
